controller:
  config:
    proxy-next-upstream: error timeout http_502
  service:
    enabled: true
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      external-dns.alpha.kubernetes.io/hostname: "ingress.rom.com"
  publishService:
    enabled: true
  scope:
    enabled: true
    namespace: argo-sandbox
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      omitClusterIP: false
  replicaCount: 1
  updateStrategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  minAvailable: 1
  resources:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 300Mi
defaultBackend:
  service:
    omitClusterIP: false
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 20Mi
  replicaCount: 1